[package]
name = "yggdrasil-appearancelib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = "0.25"
flate2 = "1.0"
byteorder = "1.5"
thiserror = "1.0"
